vim: --enable-python3interp
asteroid 2.0 which is depended by python-mode plugin only supports
python3

Otherwise the following error may happen when running
"PymodePython from pymode.lint import code_check" with python2

	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "/home/yunion/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
	    from pylama.lint.extensions import LINTERS
	  File "/home/yunion/.vim/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 44, in <module>
	    from pylama.lint.pylama_pylint import Linter
	  File "/home/yunion/.vim/bundle/python-mode/pymode/libs/pylama/lint/pylama_pylint.py", line 5, in <module>
	    from astroid import MANAGER
	  File "/home/yunion/.vim/bundle/python-mode/pymode/libs/astroid/__init__.py", line 59, in <module>
	    from astroid.exceptions import *
	  File "/home/yunion/.vim/bundle/python-mode/pymode/libs/astroid/exceptions.py", line 13, in <module>
	    from astroid import util
	  File "/home/yunion/.vim/bundle/python-mode/pymode/libs/astroid/util.py", line 148
	    yield from islice(iterator, size)
		     ^
	SyntaxError: invalid syntax